### ISSUE TITLE
Maven dependencies use an absolute path instead of one referencing the project

### ISSUE THREAD

**Issue by JamieSinn** [hoqhuuep/IslandCraft#8]
This makes it nearly impossible to make additions without having to change it to compile locally.

Please use somethiung like ${project.basedir}/lib/craftbukkit-v.jar
or just use local install depends. Much easier.

**Comment by hoqhuuep** [comment]
I agree!

**Comment by hoqhuuep** [comment]
The latest "develop" branch now uses Gradle instead of Maven. There is now only a single build script, in the root directory. This should be much easier to manage.

I recommend that you install the craftbukkit JAR to your local maven repository. Most likely you will only need to build support for the latest version (rather than all versions) so you can comment out the earlier versions in the IslandCraft-Core dependencies list (in build.gradle) before you build.
